
name: Build Armbian

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      branch:
        description: 'Kernel Select(current|edge)'
        required: false
        default: 'edge'
      release:
        description: 'Ubuntu Selsect(jammy|lunar)'
        required: false
        default: 'lunar'
      desktop:
        description: 'Armbian Desktop(yes|no)'
        required: false
        default: 'no'

env:
  REPO_URL: https://github.com/Anuo-shuo/Armbian
  REPO_BRANCH: master
  
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH Armbian
        ln -sf /workdir/Armbian $GITHUB_WORKSPACE/Armbian
        echo "NOT cp Armbian/config/boards/rock960.csc Armbian/config/boards/rock960.conf"

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    
    - name: Compile firmware(edge,lunar,cli)
      id: compile_edge_lunar_cli
      if: (github.event.inputs.branch == 'edge' && github.event.inputs.release  == 'lunar' && github.event.inputs.desktop  == 'no') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=edge RELEASE=lunar BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z

    - name: Compile firmware(current,lunar,cli)
      id: compile_current_lunar_cli
      if: (github.event.inputs.branch == 'current' && github.event.inputs.release  == 'lunar' && github.event.inputs.desktop  == 'no') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=current RELEASE=lunar BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z

    - name: Compile firmware(edge,jammy,cli)
      id: compile_edge_jammy_cli
      if: (github.event.inputs.branch == 'edge' && github.event.inputs.release  == 'lunar' && github.event.inputs.desktop  == 'no') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=edge RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z
    
    - name: Compile firmware(current,jammy,cli)
      id: compile_current_jammy_cli
      if: (github.event.inputs.branch == 'current' && github.event.inputs.release  == 'jammy' && github.event.inputs.desktop  == 'no') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=current RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z
 
    #desktop
    
    - name: Compile firmware(edge,lunar,desktop)
      id: compile_edge_lunar_desktop
      if: (github.event.inputs.branch == 'edge' && github.event.inputs.release  == 'lunar' && github.event.inputs.desktop  == 'yes') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=edge RELEASE=lunar BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z DESKTOP_ENVIRONMENT="xfce" DESKTOP_ENVIRONMENT_CONFIG_NAME="config_full" DESKTOP_APPGROUPS_SELECTED="browsers editors programming"
    
    - name: Compile firmware(current,lunar,desktop)
      id: compile_current_lunar_desktop
      if: (github.event.inputs.branch == 'current' && github.event.inputs.release  == 'lunar' && github.event.inputs.desktop  == 'yes') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=current RELEASE=lunar BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z DESKTOP_ENVIRONMENT="xfce" DESKTOP_ENVIRONMENT_CONFIG_NAME="config_full" DESKTOP_APPGROUPS_SELECTED="browsers editors programming"
    
    - name: Compile firmware(edge,jammy,desktop)
      id: compile_edge_jammy_desktop
      if: (github.event.inputs.branch == 'edge' && github.event.inputs.release  == 'lunar' && github.event.inputs.desktop  == 'yes') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=edge RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z DESKTOP_ENVIRONMENT="xfce" DESKTOP_ENVIRONMENT_CONFIG_NAME="config_full" DESKTOP_APPGROUPS_SELECTED="browsers editors programming"
    
    - name: Compile firmware(current,jammy,desktop)
      id: compile_current_jammy_desktop
      if: (github.event.inputs.branch == 'current' && github.event.inputs.release  == 'jammy' && github.event.inputs.desktop  == 'yes') 
      run: |       
        cd Armbian
        echo $PWD
        ./compile.sh  BOARD=rock960 BRANCH=current RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,7z DESKTOP_ENVIRONMENT="xfce" DESKTOP_ENVIRONMENT_CONFIG_NAME="config_full" DESKTOP_APPGROUPS_SELECTED="browsers editors programming"
  
    
    - name: Copy firmware
      id: copy
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        echo $PWD
        mkdir github_release
        ls
        cp -r ./output/debs/* ./github_release/
        cp -r ./output/images/* ./github_release/
        ls ./github_release/
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload debs directory
      uses: actions/upload-artifact@main
      if: env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: Armbian_rock960_debs
        path: Armbian/output/debs
        
    - name: Upload images directory
      uses: actions/upload-artifact@main
      if: env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: Armbian_rock960_images
        path: Armbian/output/images

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        echo $PWD
        cd Armbian/github_release
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: Armbian_rock960_release
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo $PWD
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
        
# ./compile.sh  BOARD=rock960 BRANCH=edge RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=no BUILD_ONLY=kernel KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img 
